<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="GMT Standard Time">
<General productName="Micro Focus Unified Functional Testing" productVer="15.0.2" os="" host="AO2E2E919R4"><DocLocation><![CDATA[C:\OnStack_InStoreSales\Automation\TestScripts\AO2_01_ISS_UAT_35]]></DocLocation></General>
<Doc rID="T1"   productName= "Micro Focus Unified Functional Testing"  >
<DName><![CDATA[AO2_01_ISS_UAT_35]]></DName>
<Res><![CDATA[Report]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xlsx]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/24/2021 - 12:20:54]]></Time>
<TimeTick>1621855254</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="8" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/24/2021 - 12:20:54]]></Time>
<TimeTick>1621855254</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[LoadFunctionLibrary]]></Obj>
<Details plainTxt="False" ><![CDATA[LoadFunctionLibrary function passed]]></Details>
<Time><![CDATA[5/24/2021 - 12:20:54]]></Time>
<TimeTick>1621855254</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[LoadFunctionLibrary]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:20:58]]></Time>
<TimeTick>1621855258</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Main Menu.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:20:58]]></Time>
<TimeTick>1621855258</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="13" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Main Menu.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Back Office.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:00]]></Time>
<TimeTick>1621855260</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="15" >
<Disp><![CDATA[Back Office.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["100"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:00]]></Time>
<TimeTick>1621855260</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="17" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:00]]></Time>
<TimeTick>1621855260</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1234"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:00]]></Time>
<TimeTick>1621855260</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" >
<Disp><![CDATA[Back Office Login.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Back Office Login.Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:01]]></Time>
<TimeTick>1621855261</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" >
<Disp><![CDATA[Back Office Login.Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Override.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:03]]></Time>
<TimeTick>1621855263</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="25" >
<Disp><![CDATA[Override.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Yes.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:03]]></Time>
<TimeTick>1621855263</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="27" >
<Disp><![CDATA[Yes.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:06]]></Time>
<TimeTick>1621855266</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="29" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[DtvList.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["#18"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:12]]></Time>
<TimeTick>1621855272</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="31" >
<Disp><![CDATA[DtvList.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[Include.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:17]]></Time>
<TimeTick>1621855277</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="32" >
<Disp><![CDATA[Include.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Include.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:17]]></Time>
<TimeTick>1621855277</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" >
<Disp><![CDATA[Include.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="12" Source="Action1" SourceLine="-1" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj ><![CDATA[Include Button]]></Obj>
<Details ><![CDATA[Validation of Include Button is Done]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:17]]></Time>
<TimeTick>1621855277</TimeTick>
<NodeArgs eType="User" icon="10" nRep="35" status="Passed" >
<Disp><![CDATA[Include Button]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:19]]></Time>
<TimeTick>1621855279</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Exclude.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:19]]></Time>
<TimeTick>1621855279</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="37" >
<Disp><![CDATA[Exclude.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Exclude.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:19]]></Time>
<TimeTick>1621855279</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="39" >
<Disp><![CDATA[Exclude.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="36" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Exclude Button]]></Obj>
<Details ><![CDATA[Validation of Exclude Button is Done]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:19]]></Time>
<TimeTick>1621855279</TimeTick>
<NodeArgs eType="User" icon="10" nRep="40" status="Passed" >
<Disp><![CDATA[Exclude Button]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:21]]></Time>
<TimeTick>1621855281</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Confirm.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:21]]></Time>
<TimeTick>1621855281</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="42" >
<Disp><![CDATA[Confirm.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Confirm.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:21]]></Time>
<TimeTick>1621855281</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" >
<Disp><![CDATA[Confirm.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:23]]></Time>
<TimeTick>1621855283</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="45" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[Back_2.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:23]]></Time>
<TimeTick>1621855283</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="47" >
<Disp><![CDATA[Back_2.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:26]]></Time>
<TimeTick>1621855286</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="49" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:27]]></Time>
<TimeTick>1621855287</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="51" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:27]]></Time>
<TimeTick>1621855287</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="52" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="41" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:27]]></Time>
<TimeTick>1621855287</TimeTick>
<NodeArgs eType="User" icon="10" nRep="53" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:29]]></Time>
<TimeTick>1621855289</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:29]]></Time>
<TimeTick>1621855289</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:30]]></Time>
<TimeTick>1621855290</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="58" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:30]]></Time>
<TimeTick>1621855290</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="59" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="55" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:30]]></Time>
<TimeTick>1621855290</TimeTick>
<NodeArgs eType="User" icon="10" nRep="60" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:32]]></Time>
<TimeTick>1621855292</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:32]]></Time>
<TimeTick>1621855292</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="63" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:34]]></Time>
<TimeTick>1621855294</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="65" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:34]]></Time>
<TimeTick>1621855294</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="66" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="62" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:34]]></Time>
<TimeTick>1621855294</TimeTick>
<NodeArgs eType="User" icon="10" nRep="67" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:36]]></Time>
<TimeTick>1621855296</TimeTick>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:36]]></Time>
<TimeTick>1621855296</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="70" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:37]]></Time>
<TimeTick>1621855297</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:37]]></Time>
<TimeTick>1621855297</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="69" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:37]]></Time>
<TimeTick>1621855297</TimeTick>
<NodeArgs eType="User" icon="10" nRep="74" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:39]]></Time>
<TimeTick>1621855299</TimeTick>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:39]]></Time>
<TimeTick>1621855299</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="77" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:40]]></Time>
<TimeTick>1621855300</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="79" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:40]]></Time>
<TimeTick>1621855300</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="80" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="76" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:40]]></Time>
<TimeTick>1621855300</TimeTick>
<NodeArgs eType="User" icon="10" nRep="81" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:43]]></Time>
<TimeTick>1621855303</TimeTick>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:43]]></Time>
<TimeTick>1621855303</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="84" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:44]]></Time>
<TimeTick>1621855304</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="86" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:44]]></Time>
<TimeTick>1621855304</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="87" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="83" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:44]]></Time>
<TimeTick>1621855304</TimeTick>
<NodeArgs eType="User" icon="10" nRep="88" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:46]]></Time>
<TimeTick>1621855306</TimeTick>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:46]]></Time>
<TimeTick>1621855306</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="91" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:47]]></Time>
<TimeTick>1621855307</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="93" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:47]]></Time>
<TimeTick>1621855307</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="94" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="90" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:47]]></Time>
<TimeTick>1621855307</TimeTick>
<NodeArgs eType="User" icon="10" nRep="95" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:50]]></Time>
<TimeTick>1621855310</TimeTick>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:50]]></Time>
<TimeTick>1621855310</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="98" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:51]]></Time>
<TimeTick>1621855311</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="100" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:51]]></Time>
<TimeTick>1621855311</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="101" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="97" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:51]]></Time>
<TimeTick>1621855311</TimeTick>
<NodeArgs eType="User" icon="10" nRep="102" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:53]]></Time>
<TimeTick>1621855313</TimeTick>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:53]]></Time>
<TimeTick>1621855313</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="105" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:54]]></Time>
<TimeTick>1621855314</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="107" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:54]]></Time>
<TimeTick>1621855314</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="108" >
<Disp><![CDATA[Back_2.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="104" >
<Disp><![CDATA[Oracle Retail Xstore Point]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj ><![CDATA[Back_2 button not displayed]]></Obj>
<Details ><![CDATA[Button not displayed]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:54]]></Time>
<TimeTick>1621855314</TimeTick>
<NodeArgs eType="User" icon="10" nRep="109" status="Passed" >
<Disp><![CDATA[Back_2 button not displayed]]></Disp>
</NodeArgs>
</Step>
<Step rID="T75">
<Obj plainTxt="False" ><![CDATA[Oracle Retail Xstore Point]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:56]]></Time>
<TimeTick>1621855316</TimeTick>
<Step rID="T76">
<Obj plainTxt="False" ><![CDATA[Yes.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:56]]></Time>
<TimeTick>1621855316</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="112" >
<Disp><![CDATA[Yes.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T77">
<Obj plainTxt="False" ><![CDATA[[ JavaEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:58]]></Time>
<TimeTick>1621855318</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="114" >
<Disp><![CDATA[[ JavaEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T78">
<Obj plainTxt="False" ><![CDATA[Back_2.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[5/24/2021 - 12:21:58]]></Time>
<TimeTick>1621855318</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="115" >